# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/kei2100/playground-go
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: make vet lint
      - restore_cache:
          key: playground-go-{{ .Revision }}
      - run: ls vendor/{{ .Revision }} > /dev/null 2>&1 || make vendor && touch vendor/{{ .Revision }}
      - save_cache:
          key: playground-go-{{ .Revision }}
          paths: vendor
  test:
    working_directory: /go/src/github.com/kei2100/playground-go
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - restore_cache:
          key: playground-go-{{ .Revision }}
      - run: make test
