# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/kei2100/playground-go
    docker:
      - image: circleci/golang:1.9
      - image: kei2100/mysql-initialized:5.7
        environment:
          MYSQL_ROOT_PASSWORD: pass
    steps:
      - run: dockerize -wait tcp://localhost:3306 -timeout 1m

        #      - checkout
        #      - run: rm -rf /go/bin  # for restoring /go/bin
        #      - restore_cache:
        #          key: playground-go-{{ .Revision }}
        #      - run: make setup
        #      - run: make vet lint
        #      - run: ls vendor/$CIRCLE_SHA1 > /dev/null 2>&1 || make vendor && touch vendor/$CIRCLE_SHA1
        #      - save_cache:
        #          key: playground-go-{{ .Revision }}
        #          paths:
        #            - vendor
        #            - /go/bin
        #      - run: make test
