# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/kei2100/playground-go
    docker:
      - image: circleci/golang:1.11.2
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout

      - run: rm -rf /go/bin  # for restoring /go/bin
      - restore_cache:
          key: gobin-{{ checksum "Makefile" }}
      - run: make setup
      - save_cache:
          key: gobin-{{ checksum "Makefile" }}
          paths:
            - /go/bin

      - restore_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - run: ls vendor > /dev/null 2>&1 || make vendor
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor

      - restore_cache:
          key: lint-{{ .Revision }}
      - run: ls .circleci/lintok > /dev/null 2>&1 || make vet lint && touch .circleci/lintok
      - save_cache:
          key: lint-{{ .Revision }}
          paths:
            - .circleci/lintok

      - run: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: make test.nocache
      - run:
          command: trap 'trapped' 2 3 15; sleep 100; echo 'done'
          background: true
